### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Vitalasy** [AntiCope/meteor-e621-integration#2]
Stop the element being loaded when not in-game  as it causes a funny crash

**Comment by C10udburst** [comment]
give crash log now

**Comment by Vitalasy** [comment]
> give crash log now

THAT IS A THREAT (giving log in a moment)

**Comment by C10udburst** [comment]
yes it is

<img src="https://cdn.discordapp.com/emojis/929083598827573328.webp?size=64">

**Comment by Vitalasy** [comment]
> yes it is
> 
> ![](https://camo.githubusercontent.com/7596c20009c2dc5b373b6f824a7c269a24f04180dfb987e02687cd9b3d8c039c/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3932393038333539383832373537333332382e776562703f73697a653d3634)

this may be a mistake but it was orion's logo create issue on orion rp :trollface:

**Comment by Vitalasy** [comment]
*creating

**Comment by C10udburst** [comment]
guh
