### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by TaxEvasiqn** [AntiCope/meteor-e621-integration#7]
What version is it for? I'm using dev build 1423 and it doesn't seem to show anything on the HUD.

**Comment by RegalAether** [comment]
update meteor to the latest dev build

**Comment by C10udburst** [comment]
ye this is 1.18.2 latest devbuild

**Comment by TaxEvasiqn** [comment]
theres still no image displaying im using dev build 1446

**Comment by C10udburst** [comment]
did you enable it in the hud editor? 

https://github.com/MeteorDevelopment/meteor-client/wiki#how-do-i-use-the-hud

**Comment by TaxEvasiqn** [comment]
yeah

**Comment by C10udburst** [comment]
fixed in b9caf5a4791dc0f6fbe23b1b58692dc5a5d2d14a ig

**Comment by machiecodes** [comment]
guh
